services:
  api:
    build: .
    depends_on:
      - mongodb
    ports:
      -  3000:3000
    environment:
      MONGO_URL: ${MONGO_URL}


  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: medaid

  
  